from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    username = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    # Role-based access: "single", "admin"
    role = Column(String, default="single", nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Image(Base):
    __tablename__ = "images"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    original_filename = Column(String, nullable=False)
    stored_filename = Column(String, nullable=False, unique=True)
    file_path = Column(String, nullable=False)
    file_size = Column(Integer, nullable=False)  # bytes
    preprocessed_filename = Column(String, nullable=True)
    preprocessed_path = Column(String, nullable=True)
    is_preprocessed = Column(Boolean, default=False, nullable=False)
    cv_result = Column(String, nullable=True)
    cv_confidence = Column(String, nullable=True)
    manual_correction = Column(String, nullable=True)
    # Per-image CV classification status: None / "running" / "completed" / "failed"
    reading_status = Column(String, nullable=True, default=None)
    reading_error = Column(String, nullable=True, default=None)
    # JSON array of warning keys generated by the backend (e.g. "young_cat_false_negative").
    # Frontends map each key to a localized message; kept as string to keep SQLite schema simple.
    warnings = Column(String, nullable=True, default=None)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", backref="images")
    patient_info = relationship(
        "PatientInfo", back_populates="image", uselist=False,
        cascade="all, delete-orphan",
    )


class PatientInfo(Base):
    __tablename__ = "patient_info"

    id = Column(Integer, primary_key=True, autoincrement=True)
    image_id = Column(Integer, ForeignKey("images.id"), unique=True, nullable=False)
    # Disease workflow chosen on the Home page; species is derived from it.
    disease_category = Column(String, nullable=False)
    species = Column(String, nullable=True)
    age = Column(String, nullable=True)
    sex = Column(String, nullable=True)
    breed = Column(String, nullable=True)
    area_code = Column(String, nullable=True)
    # Only used by the Tick Borne workflow; null otherwise.
    preventive_treatment = Column(Boolean, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    image = relationship("Image", back_populates="patient_info")
